### ISSUE TITLE
Handle malformed requests in API AT endpoint

### ISSUE THREAD

**Issue by carlobortolan** [Embloy/Embloy-Core#82]
Sending a malformed request header to the AT endpoint (e.g., a user JSON instead of a RT) causes an internal server error.

```
NoMethodError: undefined method `empty?' for #<User id: 3813, email: "vKhROMwZxSKquQxM@embloy.com", password_digest: "$2a$04$7SBrOyTLu78nylhcgc1pBe9u4CghL5fpXOZf/c4yyj5...", activity_status: 1, image_url: nil, first_name: "Max", last_name: "Mustermann", longitude: nil, latitude: nil, country_code: nil, postal_code: nil, city: nil, address: nil, date_of_birth: nil, user_type: "private", view_count: 0, created_at: "2023-10-24 21:15:08.464243000 +0000", updated_at: "2023-10-24 21:15:08.464243000 +0000", applications_count: 0, jobs_count: 0, user_role: "verified", application_notifications: true, twitter_url: nil, facebook_url: nil, instagram_url: nil, phone: nil, degree: nil, linkedin_url: nil>

  0) UserController User (GET: /api/v0/user/upcoming) valid normal inputs returns [204 No Content] if user does not have any jobs
     Failure/Error: (request.headers["HTTP_ACCESS_TOKEN"].nil? || request.headers["HTTP_ACCESS_TOKEN"].empty?) ? blank_error('token') : @decoded_token = AuthenticationTokenService::Access::Decoder.call(request.headers["HTTP_ACCESS_TOKEN"])[0]

     NoMethodError:
       undefined method `empty?' for #<User id: 3813, email: "vKhROMwZxSKquQxM@embloy.com", password_digest: "$2a$04$7SBrOyTLu78nylhcgc1pBe9u4CghL5fpXOZf/c4yyj5...", activity_status: 1, image_url: nil, first_name: "Max", last_name: "Mustermann", longitude: nil, latitude: nil, country_code: nil, postal_code: nil, city: nil, address: nil, date_of_birth: nil, user_type: "private", view_count: 0, created_at: "2023-10-24 21:15:08.464243000 +0000", updated_at: "2023-10-24 21:15:08.464243000 +0000", applications_count: 0, jobs_count: 0, user_role: "verified", application_notifications: true, twitter_url: nil, facebook_url: nil, instagram_url: nil, phone: nil, degree: nil, linkedin_url: nil>
     # ./app/controllers/api/v0/api_controller.rb:11:in `verify_access_token'
     # ./spec/requests/api/v0/user_controller_spec.rb:252:in `block (5 levels) in <top (required)>'

```
